apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: db
  name: db
  namespace: default
spec:
  replicas: 1
  selector:
    service: db
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: anothernotverysecurepassword
        - name: POSTGRES_USER
          value: adventure
        image: postgres
        imagePullPolicy: ""
        name: db
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
