apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: ldap
  name: ldap
  namespace: default
spec:
  replicas: 1
  selector:
    service: ldap
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: ldap
    spec:
      containers:
      - env:
        - name: LDAP_ADMIN_PASSWORD
          value: notaverysecurepassword
        - name: LDAP_DOMAIN
          value: adventure.org
        - name: LDAP_ORGANISATION
          value: Adventure
        image: quay.io/colinn/adventure-ldap
        imagePullPolicy: ""
        name: ldap
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
