apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    service: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: nginx
    spec:
      containers:
      - image: quay.io/colinn/adventure-nginx
        imagePullPolicy: ""
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /var/cache/nginx
          name: cache
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /data/cache
        name: cache
status:
  replicas: 0
