apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: site
  name: site
  namespace: default
spec:
  replicas: 1
  selector:
    service: site
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: site
    spec:
      containers:
      - env:
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: adventure
              key: connection-string
        image: quay.io/colinn/adventure-site:v2
        imagePullPolicy: ""
        name: site
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
