apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: site
  namespace: default
  labels:
    service: site

spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: site
    spec:
      containers:
      - env:
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: adventure
              key: connection-string
        image: quay.io/colinn/adventure-site:v3
        imagePullPolicy: ""
        name: site
        resources: {}
        ports:
          - containerPort: 3000
            name: http
            protocol: TCP

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status:
  replicas: 0
