apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: ssh
  name: ssh
  namespace: default
spec:
  replicas: 1
  selector:
    service: ssh
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: ssh
    spec:
      containers:
      - image: quay.io/colinn/adventure-ssh
        imagePullPolicy: ""
        name: ssh
        resources: {}
        volumeMounts:
        - mountPath: /var/cache/nginx
          name: cache
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /data/cache
        name: cache
status:
  replicas: 0
