"""empty message

Revision ID: 0e845d17c890
Revises: 24bb227a82fa
Create Date: 2016-08-12 22:14:36.607919

"""

# revision identifiers, used by Alembic.
revision = '0e845d17c890'
down_revision = '24bb227a82fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ldap_auth', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ldap_auth')

    ### end Alembic commands ###
