"""empty message

Revision ID: 12dbcc02f545
Revises: 8bf71d334682
Create Date: 2016-07-12 22:21:51.868514

"""

# revision identifiers, used by Alembic.
revision = '12dbcc02f545'
down_revision = '8bf71d334682'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lunch_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('order', sa.Text(), nullable=False),
    sa.Column('order_for', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_for'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lunch_order')
    ### end Alembic commands ###
