"""empty message

Revision ID: 24bb227a82fa
Revises: 7b0843b4944f
Create Date: 2016-08-09 23:18:44.834190

"""

# revision identifiers, used by Alembic.
revision = '24bb227a82fa'
down_revision = '7b0843b4944f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    t = op.create_table('office_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('number_prefix', sa.String(length=128), nullable=False),
    sa.Column('main_number', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.bulk_insert(t, [
        {
            'name': 'Main Office',
            'number_prefix': '555-1',
            'main_number': '555-13211-3221',
        },
        {
            'name': 'Babel Office',
            'number_prefix': '555-2',
            'main_number': '555-21111-3221',
        },
        {
            'name': 'Office Minnows',
            'number_prefix': '555-9',
            'main_number': '555-99911-3221',
        },
    ])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('office_numbers')
    ### end Alembic commands ###
