"""empty message

Revision ID: 31c517493444
Revises: 12dbcc02f545
Create Date: 2016-08-03 18:37:36.132345

"""

# revision identifiers, used by Alembic.
revision = '31c517493444'
down_revision = '12dbcc02f545'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column('location')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=256), nullable=False))

    ### end Alembic commands ###
