"""empty message

Revision ID: 8bf71d334682
Revises: 1e4c788b2c90
Create Date: 2016-05-26 20:38:50.828261

"""

# revision identifiers, used by Alembic.
revision = '8bf71d334682'
down_revision = '1e4c788b2c90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('link_text', sa.String(length=256), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menus')
    ### end Alembic commands ###
