"""empty message

Revision ID: a83fe752a741
Revises: 31c517493444
Create Date: 2016-08-06 21:38:00.617319

"""

# revision identifiers, used by Alembic.
revision = 'a83fe752a741'
down_revision = '31c517493444'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    ### end Alembic commands ###
