"""empty message

Revision ID: db672000e814
Revises: a83fe752a741
Create Date: 2016-08-08 22:35:07.725967

"""

# revision identifiers, used by Alembic.
revision = 'db672000e814'
down_revision = 'a83fe752a741'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunch_order', schema=None) as batch_op:
        batch_op.create_foreign_key('order_id_fkey', 'order', ['order_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunch_order', schema=None) as batch_op:
        batch_op.drop_constraint('order_id_fkey', type_='foreignkey')

    ### end Alembic commands ###
