apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: db
  namespace: default
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    service: db
status:
  loadBalancer: {}
