apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: site
  namespace: default
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    service: site
status:
  loadBalancer: {}
