apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ssh
  namespace: default
spec:
  ports:
    - port: 22
      protocol: TCP
      targetPort: 22
  selector:
    service: ssh
status:
  loadBalancer: {}
